#ifndef test_nonterminals_h
#define test_nonterminals_h

/**
 *  \brief  Grammar non-terminals enumeration
 *
 *  The code is generated; do NOT change it, manually.
 *
 *  This file is part of code generated by CTXFryer
 *  while producing lexical analyser source code.
 *
 *  \date  2012/08/24
 */


#define NT_F 0  /**< ID 0x00000012 */
#define NT_T 1  /**< ID 0x00000013 */
#define NT_E 2  /**< ID 0x00000014 */

/** Augmented grammar root, ID 0x00000011 */
#define NT__E 3

#endif  /* end of #ifndef test_nonterminals_h */
