#ifndef CTXFryer__lexical_items_h
#define CTXFryer__lexical_items_h

/**
 *  \brief   FSA : Accepted lexical items
 *
 *  The code is generated; do NOT change it, manually.
 *
 *  This file is part of code generated by CTXFryer
 *  while producing lexical analyser source code.
 *
 *  \date  2012/06/15
 */


#define LEXI_number 1  /**< Lexical item for "number" terminal symbol */
#define LEXI_add    2  /**< Lexical item for "add"    terminal symbol */
#define LEXI_mul    3  /**< Lexical item for "mul"    terminal symbol */
#define LEXI_rpar   4  /**< Lexical item for "rpar"   terminal symbol */
#define LEXI_lpar   5  /**< Lexical item for "lpar"   terminal symbol */

#define LEXICNT 6  /**< Number of lexical items (including EoF) */

#endif /* end of #ifndef CTXFryer__lexical_items_h */
