#ifndef CTXFryer__test_fsa_table_h
#define CTXFryer__test_fsa_table_h

/**
 *  \brief   Lexical analyser FSA declaration
 *
 *  This file is part of code generated by CTXFryer
 *  while producing lexical analyser source code.
 *
 *  \date  2012/06/15
 */

#include "fsa.h"


/**
 *  \brief  Lexical analyser FSA
 *
 *  The FSA tables are generated.
 *  Don't change the code; change the definition, if required.
 */
extern const fsa_t test_fsa;

#endif  /* end of #ifndef CTXFryer__test_fsa_table_h */
