#ifndef builtin_attr_h
#define builtin_attr_h

/**
 *  \brief   Built-in attributes
 *
 *  Built-in attributes, their evaluators & destructors.
 *
 *  This file is part of code generated by CTXFryer
 *  while producing syntax analyser source code.
 *
 *  \date  2013/03/28
 */

#include "attribute.h"
#include "token.h"


/**
 *  \brief  Lexical token getter
 *
 *  \param  attr   Attribute
 *  \param  token  Target
 *
 *  \retval ATTR_EVAL_OK    on success
 *  \retval ATTR_EVAL_ERROR if the associated parse tree node
 *                          doesn't represent a terminal on the input
 */
attr_eval_status_t builtin__get_token(attr_handle_t *attr, token_t **token);

#endif  /* end of #ifndef builtin_attr_h */
