#ifndef parser_tables_h
#define parser_tables_h

/**
 *  \brief   LR(1) parser tables declarations
 *
 *  This file is part of code generated by CTXFryer
 *  while producing syntax analyser source code.
 *
 *  \date  2012/08/24
 */

#include "syntax_analyser.h"


/**
 *  \brief  LR(1) action table
 *
 *  The parser tables are generated.
 *  Don't change the code; change the definition, if required.
 */
extern const lr1_action_tab_t action_tab;


/**
 *  \brief  LR(1) goto table
 *
 *  The parser tables are generated.
 *  Don't change the code; change the definition, if required.
 */
extern const lr1_goto_tab_t goto_tab;


/**
 *  \brief  LR(1) rules info table
 *
 *  The parser tables are generated.
 *  Don't change the code; change the definition, if required.
 */
extern const lr1_rule_tab_t rule_tab;


/**
 *  \brief  Attribute definitions table
 *
 *  The parser tables are generated.
 *  Don't change the code; change the definition, if required.
 */
extern const attribute_tab_t attribute_tab;

#endif  /* end of #ifndef parser_tables_h */
