/**
 *  \brief   Built-in attributes
 *
 *  This file is part of code generated by CTXFryer
 *  while producing syntax analyser source code.
 *
 *  \date  2013/03/31
 */

#include "builtin_attr.h"
#include "attribute.h"
#include "ptree.h"
#include "token.h"

#include <assert.h>


/*
 * Attribute built-in functions definitions
 */

attr_eval_status_t builtin__get_token(attr_handle_t *attr, token_t **token) {
    assert(NULL != attr);
    assert(NULL != token);

    ptree_node_t *ptnode = attr_ptree_node(attr);

    assert(NULL != ptnode);

    la_item_t *lex_item = ptree_tnode_item(ptnode);

    if (NULL == lex_item) return ATTR_EVAL_ERROR;

    *token = lex_item;  /* la_item_t implements token */

    return ATTR_EVAL_OK;
}
