#!/usr/bin/perl

use strict;
use warnings;

use CTXFryer::ProjectDef;

use CTXFryer::Logging qw(:all);

# Default log level
$CTXFryer::Logging::threshold = "INFO";

my $project_def = new CTXFryer::ProjectDef($ARGV[0]) || exit(1);
my $metainfo    = $project_def->metaInfo()           || exit(0);

print(join(" ", $metainfo->targetLanguages()), "\n");
