#ifndef fsa_table_h
#define fsa_table_h

/**
 *  \brief   Lexical analyser FSA declaration
 *
 *  This file is part of code generated by CTXFryer
 *  while producing lexical analyser source code.
 *
 *  \date  2012/06/15
 */

#include "ctx-fryer-c-rt/fsa.h"


/**
 *  \brief  Lexical analyser FSA
 *
 *  The FSA tables are generated.
 *  Don't change the code; change the definition, if required.
 */
extern const fsa_t fsa;

#endif  /* end of #ifndef fsa_table_h */
