/**
 *  \brief   Project-specific parser definition
 *
 *  This file is part of code generated by CTXFryer
 *  while producing parser source code.
 *
 *  \date  2012/09/05
 */

#include "parser.h"
#include "lexical_items.h"
#include "fsa_table.h"
#include "parser_tables.h"

#include "ctx-fryer-c-rt/syntax_analyser.h"


syxa_t *parser_create(syxa_t *parser,
                      size_t  pda_stack_cap_mul,
                      size_t  pda_stack_limit,
                      int     reduct_log_enabled,
                      size_t  reduct_stack_cap_mul,
                      size_t  reduct_stack_limit,
                      int     parse_tree_enabled)
{
    return sa_create(parser,
        /* Fixed arguments */
        &fsa, LEXICNT,
        &action_tab, &goto_tab, &rule_tab, &attribute_tab,

        /* Inherited arguments */
        pda_stack_cap_mul, pda_stack_limit,
        reduct_log_enabled,
        reduct_stack_cap_mul, reduct_stack_limit,
        parse_tree_enabled);
}
